import { FloorPlan } from '@/types';
import { FURNITURE_CATALOG } from '@/data/furniture';

export interface ShoppingListItem {
  id: string;
  furnitureId: string;
  name: string;
  emoji: string;
  category: string;
  width: number;
  depth: number;
  height: number;
  price: number;
  quantity: number;
  purchased: boolean;
  roomName: string;
}

const CATEGORY_PRICE_RANGES: Record<string, [number, number]> = {
  seating: [150, 1800],
  tables: [80, 1200],
  storage: [100, 900],
  beds: [300, 2500],
  lighting: [30, 500],
  decor: [20, 300],
  kitchen: [200, 3000],
  bathroom: [100, 1500],
  office: [80, 800],
  outdoor: [60, 600],
};

function mockPrice(furnitureId: string, category: string): number {
  const range = CATEGORY_PRICE_RANGES[category] ?? [50, 500];
  // Deterministic pseudo-random based on furnitureId so price is stable
  let hash = 0;
  for (let i = 0; i < furnitureId.length; i++) {
    hash = (hash * 31 + furnitureId.charCodeAt(i)) & 0xffffffff;
  }
  const t = Math.abs(hash % 1000) / 1000;
  const raw = range[0] + t * (range[1] - range[0]);
  // Round to nearest $10
  return Math.round(raw / 10) * 10;
}

export function generateShoppingList(project: FloorPlan): ShoppingListItem[] {
  console.log('[ShoppingList] Generating list for project:', project.id, project.name);

  // Map: furnitureId+roomId -> ShoppingListItem (for deduplication within same room)
  const itemMap = new Map<string, ShoppingListItem>();

  for (const room of project.rooms) {
    for (const placed of room.placedItems) {
      const furniture = FURNITURE_CATALOG.find(f => f.id === placed.furnitureId);
      if (!furniture) continue;

      const key = `${placed.furnitureId}__${room.id}`;
      if (itemMap.has(key)) {
        const existing = itemMap.get(key)!;
        itemMap.set(key, { ...existing, quantity: existing.quantity + 1 });
      } else {
        const price = mockPrice(furniture.id, furniture.category);
        itemMap.set(key, {
          id: key,
          furnitureId: furniture.id,
          name: furniture.name,
          emoji: furniture.emoji,
          category: furniture.category,
          width: furniture.width,
          depth: furniture.depth,
          height: furniture.height,
          price,
          quantity: 1,
          purchased: false,
          roomName: room.name,
        });
      }
    }
  }

  const items = Array.from(itemMap.values());
  console.log('[ShoppingList] Generated', items.length, 'unique items');
  return items;
}

export function calculateTotal(items: ShoppingListItem[]): number {
  return items.reduce((sum, item) => sum + item.price * item.quantity, 0);
}

export function formatShoppingListAsText(project: FloorPlan, items: ShoppingListItem[]): string {
  const total = calculateTotal(items);
  const lines: string[] = [
    `🛒 Shopping List — ${project.name}`,
    `Generated by SpaceCraft 3D`,
    ``,
  ];

  // Group by category
  const grouped = groupByCategory(items);
  for (const [category, catItems] of Object.entries(grouped)) {
    const catTotal = calculateTotal(catItems);
    const label = category.charAt(0).toUpperCase() + category.slice(1);
    lines.push(`── ${label} ($${catTotal.toLocaleString()}) ──`);
    for (const item of catItems) {
      const check = item.purchased ? '✓' : '○';
      lines.push(`${check} ${item.emoji} ${item.name} × ${item.quantity}  $${(item.price * item.quantity).toLocaleString()}`);
      lines.push(`   ${item.width}W × ${item.depth}D × ${item.height}H cm  (${item.roomName})`);
    }
    lines.push('');
  }

  lines.push(`Total: $${total.toLocaleString()}`);
  return lines.join('\n');
}

export function groupByCategory(items: ShoppingListItem[]): Record<string, ShoppingListItem[]> {
  const result: Record<string, ShoppingListItem[]> = {};
  for (const item of items) {
    if (!result[item.category]) result[item.category] = [];
    result[item.category].push(item);
  }
  return result;
}
